package com.brainchain.career_counselling.Career_Counselling.service;

import com.brainchain.career_counselling.Career_Counselling.dto.CareerSuggestion;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfReportService {

    public byte[] generatePdf(CareerSuggestion suggestion, List<String> colleges) {
        try {
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter writer = PdfWriter.getInstance(document, out);

            document.addTitle("Career Counselling Report");
            document.addAuthor("BrainChain AI");
            document.addSubject("Career + College Recommendations");
            document.addKeywords("career, counselling, education, AI");
            document.addCreationDate();

            document.open();

            // Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLUE);
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.DARK_GRAY);

            // Header Title
            Paragraph header = new Paragraph("Career Counselling Report", titleFont);
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);
            document.add(Chunk.NEWLINE);

            // Summary
            document.add(new Paragraph("Summary", sectionFont));
            document.add(new Paragraph(suggestion.getSummary(), normalFont));
            document.add(Chunk.NEWLINE);

            // Career
            document.add(new Paragraph("Recommended Career(s)", sectionFont));
            document.add(new Paragraph(suggestion.getCareer(), normalFont));
            document.add(new Paragraph("Score: " + suggestion.getScore(), normalFont));
            document.add(Chunk.NEWLINE);

            // Colleges
            document.add(new Paragraph("Top College Recommendations", sectionFont));
            if (colleges != null && !colleges.isEmpty()) {
                for (String college : colleges) {
                    document.add(new Paragraph("• " + college, normalFont));
                }
            } else {
                document.add(new Paragraph("No specific colleges found for this career.", normalFont));
            }

            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by BrainChain Career Counselling", 
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, BaseColor.GRAY));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            writer.close();

            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }
}
